services:
  - type: web
    name: halcon-blanco-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000

  - type: static_site
    name: halcon-blanco-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_API_BASE
        value: "https://halcon-blanco-backend.onrender.com"
